// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2b9MJwrTxKrlm_9iNMc_ihQfrb0uKAOI',
    appId: '1:656121260272:web:2f047725ff149aaaf57a35',
    messagingSenderId: '656121260272',
    projectId: 'digitalzonehn',
    authDomain: 'digitalzonehn.firebaseapp.com',
    storageBucket: 'digitalzonehn.firebasestorage.app',
    measurementId: 'G-VG2BC64R4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAwnmhUTniq_uxfWFQFTUDESQgWerztqw',
    appId: '1:656121260272:android:47320d3df90bd5c0f57a35',
    messagingSenderId: '656121260272',
    projectId: 'digitalzonehn',
    storageBucket: 'digitalzonehn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgz3_Hsv1laoESdkHSNxAOM6SDhijfnv0',
    appId: '1:656121260272:ios:48eeb1e566d13401f57a35',
    messagingSenderId: '656121260272',
    projectId: 'digitalzonehn',
    storageBucket: 'digitalzonehn.firebasestorage.app',
    iosBundleId: 'com.example.digitalzonehn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgz3_Hsv1laoESdkHSNxAOM6SDhijfnv0',
    appId: '1:656121260272:ios:48eeb1e566d13401f57a35',
    messagingSenderId: '656121260272',
    projectId: 'digitalzonehn',
    storageBucket: 'digitalzonehn.firebasestorage.app',
    iosBundleId: 'com.example.digitalzonehn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2b9MJwrTxKrlm_9iNMc_ihQfrb0uKAOI',
    appId: '1:656121260272:web:e0730a12c8cb167af57a35',
    messagingSenderId: '656121260272',
    projectId: 'digitalzonehn',
    authDomain: 'digitalzonehn.firebaseapp.com',
    storageBucket: 'digitalzonehn.firebasestorage.app',
    measurementId: 'G-1Y658467KD',
  );
}
