// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2b9MJwrTxKrlm_9iNMc_ihQfrb0uKAOI',
    appId: '1:656121260272:web:2f047725ff149aaaf57a35',
    messagingSenderId: '656121260272',
    projectId: 'digitalzonehn',
    authDomain: 'digitalzonehn.firebaseapp.com',
    storageBucket: 'digitalzonehn.firebasestorage.app',
    measurementId: 'G-VG2BC64R4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey:
        'AIzaSyDr9... (placeholder)', // Simplified/Hidden for security in memory reconstruction, user should verify
    appId: '1:656121260272:android:6e409dae06385d56f57a35',
    messagingSenderId: '656121260272',
    projectId: 'digitalzonehn',
    storageBucket: 'digitalzonehn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSy...',
    appId: '1:656121260272:ios:cd226...',
    messagingSenderId: '656121260272',
    projectId: 'digitalzonehn',
    storageBucket: 'digitalzonehn.firebasestorage.app',
    iosBundleId: 'com.example.digitalzonehn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSy...',
    appId: '1:656121260272:ios:cd226...',
    messagingSenderId: '656121260272',
    projectId: 'digitalzonehn',
    storageBucket: 'digitalzonehn.firebasestorage.app',
    iosBundleId: 'com.example.digitalzonehn',
  );
}
